### ISSUE TITLE
500 Internal error on multimedia benchmarks as well. Please assist

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#115]
(python-venv) jchigu@SEBS:~$ curl 172.17.0.3:9000 --request POST --data '{"bucket": {                                 
        "input": "210.thumbnailer-0-input-8f4da427-ac91-4f",
        "output": "210.thumbnailer-0-output-b78816aa-0c74-40"
      },
      "object": {
        "height": 200,
        "key": "0_action-adrenaline-adventure-1047051.jpg",
        "width": 200
      }
}' --header 'Content-Type: application/json'

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>TypeError(&#039;an integer is required (got type NoneType)&#039;)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/function/function/function.py&quot;, line 9, in handler
    graph = igraph.Graph.Barabasi(size, 10)
TypeError: an integer is required (got type NoneType)
</pre>
        </body>
    </html>
(python-venv) jchigu@SEBS:~$

**Comment by mcopik** [comment]
This seems to be a problem as in #114 - there is the same code of graph benchmark in the exception stack trace.

Closing as a duplicate.
