### ISSUE TITLE
500 internal error on 020.network-benchmark. Please assist

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#117]
(python-venv) jchigu@SEBS:~$ curl 172.17.0.3:9000 --request POST --data '{"output-bucket": "020.network-benchmark-0-output-51aa6603-d12a-4d"}' --header 'Content-Type: application/json'

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>TypeError(&#039;an integer is required (got type NoneType)&#039;)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/function/function/function.py&quot;, line 8, in handler
    sleep(sleep_time)
TypeError: an integer is required (got type NoneType)
</pre>
        </body>
    </html>
(python-venv) jchigu@SEBS:~$

**Comment by mcopik** [comment]
Dear @jchigu - all benchmarks whose number starts with the digit 0 are internal microbenchmarks used by specific experiments. They are not intended to be directly invoked by users, so they are not included in the [benchmark list](https://github.com/spcl/serverless-benchmarks/blob/master/docs/benchmarks.md) - please refer to this document to find all benchmarks.

I will add a warning clarifying the status of `0xy` benchmarks to the list.
