### ISSUE TITLE
Access Key for 210.thumbnailer does not exist on our records

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#120]
(python-venv) jchigu@SEBS:~$curl 172.17.0.3:9000 --request POST -o testresult210thumbnailer.json --data '{"bucket": {                                 
        "input": "210.thumbnailer-0-input-d767f05b-3d5f-48",
        "output": "210.thumbnailer-0-output-c699682c-3fc2-41"
      },
      "object": {
        "height": 200,
        "key": "0_action-adrenaline-adventure-1047051.jpg",
        "width": 200
      }
}' --header 'Content-Type: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3075  100  2799  100   276   3436    338 --:--:-- --:--:-- --:--:--  3853

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://172.17.0.3:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
              <h2>Exception:</h2>
              <pre>S3Error(&#039;S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /210.thumbnailer-0-input-d767f05b-3d5f-48, request_id: 1745E58DAA294857, host_id: d15109e7-a865-4862-8c2f-c6ef05e87e1f, bucket_name: 210.thumbnailer-0-input-d767f05b-3d5f-48&#039;)</pre>
              <h2>Traceback:</h2>
              <pre>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 868, in _handle
    return route.call(**args)
  File &quot;/usr/local/lib/python3.7/site-packages/bottle.py&quot;, line 1748, in wrapper
    rv = callback(*a, **ka)
  File &quot;/sebs/server.py&quot;, line 17, in flush_log
    ret = function.handler(request.json)
  File &quot;/function/function/function.py&quot;, line 72, in handler
    client.download(input_bucket, key, download_path)
  File &quot;/function/function/storage.py&quot;, line 37, in download
    self.client.fget_object(bucket, file, filepath)
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 1037, in fget_object
    version_id=version_id,
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 1864, in stat_object
    query_params=query_params,
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 394, in _execute
    region = self._get_region(bucket_name, None)
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 465, in _get_region
    query_params={&quot;location&quot;: &quot;&quot;},
  File &quot;/usr/local/lib/python3.7/site-packages/minio/api.py&quot;, line 380, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /210.thumbnailer-0-input-d767f05b-3d5f-48, request_id: 1745E58DAA294857, host_id: d15109e7-a865-4862-8c2f-c6ef05e87e1f, bucket_name: 210.thumbnailer-0-input-d767f05b-3d5f-48
</pre>
        </body>
    </html>

**Comment by mcopik** [comment]
@jchigu This error indicates that the access key does not match the current Minio instance. Each Minio instance has unique access and secret keys that must be encoded in the configuration. In the [documentation](docs/usage.md#Local), we provide the command to copy the storage configuration to the function configuration, including this pair of keys:

```
jq --argfile file1 out_storage.json '.deployment.local.storage = $file1 ' config/example.json > config/local_deployment.json
```

This needs to be done for each Minio instance. Is it possible that you restarted the storage instance but did not update the configuration?

I recommend restarting both storage and function instances, making sure that you create configurations according to the documentation (each step is necessary!), and then trying to call the function again. If the issue  persists, then please post the output of starting storage container (`./sebs.py storage start`) and attach the JSON configuration used to start function instances.

**Comment by mcopik** [comment]
@jchigu Does this issue still appear? If yes, then can you please provide more information?

**Comment by mcopik** [comment]
Closing down - if the issue still persists, then please reopen with updated information instead of opening new ones.
