### ISSUE TITLE
curl: (7) Failed to connect to 172.17.0.3 port 9000 after 3069 ms: No route to host

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#124]
I created a new VM and downloaded latest serverless-benchmaks-master. Now I am getting the following errors:
1. its no longer displaying outputs of each stage
2. step 3 the out_benchmark.json is not being created hence the message 
                   (python-venv) jchigu@linux:~$ cat out_benchmark.json
                   cat: out_benchmark.json: No such file or directory
3. step4 is returning the following message:
(python-venv) jchigu@linux:~$ curl 172.17.0.3:9000 --request POST --data '{"random_len": 10,"username": "testname"}' --header   'Content-Type: application/json'
curl: (7) Failed to connect to 172.17.0.3 port 9000 after 3069 ms: No route to host
============================================================
(python-venv) jchigu@linux:~$ ip route
default via 10.0.2.2 dev enp0s3 proto dhcp metric 100 
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15 metric 100 
169.254.0.0/16 dev enp0s3 scope link metric 1000 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
(python-venv) jchigu@linux:~$ 
=============================================================
(python-venv) jchigu@linux:~$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:83:0c:5b brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute enp0s3
       valid_lft 83765sec preferred_lft 83765sec
    inet6 fe80::1527:2317:2d23:a2f3/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:85:05:eb:6c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
(python-venv) jchigu@linux:~$ 

===========================================================
The following is the full listing for local:
(python-venv) jchigu@linux:~$ ./sebs.py storage start minio --port 9011 --output-json out_storage.json
(python-venv) jchigu@linux:~$ cat out_storage.json
{
  "address": "172.17.0.2:9000",
  "mapped_port": 9011,
  "access_key": "tNIeYNucyYxvctujvP5zI4tKyXzyPAONo9o7ozWzQVc",
  "secret_key": "31434ce813f5ba6502c9c68797136a402ed28aaba1888f76452ee4a4013f2d3d",
  "instance_id": "89df9a9180f7999d930fd0ef49991a836bdc1fefe01cc689a491b1cafd1bcfe5",
  "input_buckets": [],
  "output_buckets": [],
  "type": "minio"
(python-venv) jchigu@linux:~$ jq --argfile file1 out_storage.json '.deployment.local.storage = $file1 ' config/example.json > config/local_deployment.jsonn
(python-venv) jchigu@linux:~$ cat config/local_deployment.json
{
  "experiments": {
    "deployment": "openwhisk",
    "update_code": false,
    "update_storage": false,
    "download_results": false,
    "runtime": {
      "language": "python",
      "version": "3.7"
    },
    "type": "invocation-overhead",
    "perf-cost": {
      "benchmark": "110.dynamic-html",
      "experiments": [
        "cold",
        "warm",
        "burst",
        "sequential"
      ],
      "input-size": "test",
      "repetitions": 50,
      "concurrent-invocations": 50,
      "memory-sizes": [
        128,
        256
      ]
    },
    "network-ping-pong": {
      "invocations": 50,
      "repetitions": 1000,
      "threads": 1
    },
    "invocation-overhead": {
      "repetitions": 5,
      "N": 20,
      "type": "payload",
      "payload_begin": 1024,
      "payload_end": 6251000,
      "payload_points": 20,
      "code_begin": 1048576,
      "code_end": 261619712,
      "code_points": 20
    },
    "eviction-model": {
      "invocations": 1,
      "function_copy_idx": 0,
      "repetitions": 5,
      "sleep": 1
    }
  },
  "deployment": {
    "name": "aws",
    "aws": {
      "region": "us-east-1",
      "lambda-role": ""
    },
    "azure": {
      "region": "westeurope"
    },
    "gcp": {
      "region": "europe-west1",
      "project_name": "",
      "credentials": ""
    },
    "local": {
      "storage": {
        "address": "172.17.0.2:9000",
        "mapped_port": 9011,
        "access_key": "tNIeYNucyYxvctujvP5zI4tKyXzyPAONo9o7ozWzQVc",
        "secret_key": "31434ce813f5ba6502c9c68797136a402ed28aaba1888f76452ee4a4013f2d3d",
        "instance_id": "89df9a9180f7999d930fd0ef49991a836bdc1fefe01cc689a491b1cafd1bcfe5",
        "input_buckets": [],
        "output_buckets": [],
        "type": "minio"
      }
    },
    "openwhisk": {
      "shutdownStorage": false,
      "removeCluster": false,
      "wskBypassSecurity": "true",
      "wskExec": "wsk",
      "experimentalManifest": false,
      "docker_registry": {
        "registry": "",
        "username": "",
        "password": ""
      },
      "storage": {
        "address": "",
        "mapped_port": -1,
        "access_key": "",
        "secret_key": "",
        "instance_id": "",
        "input_buckets": [],
        "output_buckets": [],
        "type": "minio"
      }
    }
  }
}
(python-venv) jchigu@linux:~$ ./sebs.py local start 110.dynamic-html test out_benchmark.json --config config/local_deployment.json --deployments 1
(python-venv) jchigu@linux:~$ cat out_benchmark.json
cat: out_benchmark.json: No such file or directory
(python-venv) jchigu@linux:~$ curl 172.17.0.3:9000 --request POST --data '{"random_len": 10,"username": "testname"}' --header 'Content-Type: application/json'
curl: (7) Failed to connect to 172.17.0.3 port 9000 after 3069 ms: No route to host
(python-venv) jchigu@linux:~$ ./sebs.py local stop out_benchmark.json
./sebs.py storage stop out_storage.json
(python-venv) jchigu@linux:~$

**Comment by mcopik** [comment]
@jchigu The error indicates there's no process listening on port `9000`. It's likely there is no benchmark container running - you can verify that by running `docker ps -a`.

You should see output from the `./sebs.py local start` - if there's no output, then likely something has gone wrong. Furthermore, the lack of `out_benchmark.json` file suggests that the container has not been started - which would explain the `curl` error.

When running your commands, the `local start` throws an error because you stored storage updates to file `config/local_deployment.jsonn` but passed `config/local_deployment.json` to starting benchmark (typo in file extension). However, you should still see an error, similar to the one here:

```console
ERROR:root:[Errno 2] No such file or directory: 'config/local_deployment.json'
```

**Comment by mcopik** [comment]
@jchigu Does this issue still appear? If yes, then can you please provide more information?
