### ISSUE TITLE
KeyError: 'memory_measurements'

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#128]
This error appears when stopping containers

====================================================================
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py storage start minio --port 9011 --output-json out_storage.json
13:01:51,493 INFO root: Starting storage Storage.MINIO on port 9011.
13:01:51,494 INFO minio.Minio-8fab: Minio storage ACCESS_KEY=S25kOglnMcLP2w9CPB49AdqzPt6DW7E8FtntY8CldZs
13:01:51,494 INFO minio.Minio-8fab: Minio storage SECRET_KEY=01c763f47e9ed199ee2addb8d76d98c77b4bf1a0d527908f4a4324fee07eee65
13:01:52,678 INFO minio.Minio-8fab: Starting minio instance at 172.17.0.2:9000
13:01:52,679 INFO root: Writing storage configuration to out_storage.json.
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ jq --argfile file1 out_storage.json '.deployment.local.storage = $file1 ' config/example.json > config/local_deployment.json
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py local start 110.dynamic-html test out_benchmark.json --config config/local_deployment.json --deployments 1
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ curl 172.17.0.3:9000 --request POST --data '{"random_len": 10,"username": "testname"}' --header 'Content-Type: application/json'
{"begin": "1677754956.117377", "end": "1677754956.229366", "request_id": "eed5087f-fb7c-4979-b59b-90e8ed0ac443", "is_cold": false, "result": {"output": {"result": "<!DOCTYPE html>\n<html>\n  <head>\n    <title>Randomly generated data.</title>\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n    <style type=\"text/css\">\n      .container {\n        max-width: 500px;\n        padding-top: 100px;\n      }\n    </style>\n  </head>\n  <body>\n    <div class=\"container\">\n      <p>Welcome testname!</p>\n      <p>Data generated at: 2023-03-02 11:02:36.229450!</p>\n      <p>Requested random numbers:</p>\n      <ul>\n        \n        <li>577961</li>\n        \n        <li>35568</li>\n        \n        <li>113796</li>\n        \n        <li>997255</li>\n        \n        <li>531069</li>\n        \n        <li>969490</li>\n        \n        <li>253819</li>\n        \n        <li>376713</li>\n        \n        <li>715493</li>\n        \n        <li>724617</li>\n        \n      </ul>\n    </div>\n  </body>\n</html>"}}}(python-venv) jchigu@SeBS:~/serverless-benchmarks$ 
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py local stop out_benchmark.json
./sebs.py storage stop out_storage.json
13:02:57,748 ERROR root: 'memory_measurements'
Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 32, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 449, in stop
    procs = json.load(file)["memory_measurements"]
KeyError: 'memory_measurements'
13:02:57,749 INFO root: # Experiments failed! See out.log for details
13:02:59,68 INFO root: Stopping storage deployment of minio.
13:02:59,130 INFO minio.Minio-9145: Stopping minio container at 172.17.0.2:9000.
13:03:00,755 INFO minio.Minio-9145: Stopped minio container at 172.17.0.2:9000.
13:03:00,756 INFO root: Stopped storage deployment of minio.
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ docker ps -a
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                      PORTS     NAMES
2c32b1425ca3   spcleth/serverless-benchmarks:run.local.python.3.7     "/sebs/entrypoint.sh…"   2 minutes ago    Up 2 minutes                          affectionate_shtern
1b7bd595216e   spcleth/serverless-benchmarks:build.local.python.3.7   "/sebs/entrypoint.sh…"   51 minutes ago   Exited (1) 51 minutes ago             affectionate_morse
0fa185899ccb   spcleth/serverless-benchmarks:build.local.python.3.7   "/sebs/entrypoint.sh…"   16 hours ago     Exited (1) 16 hours ago               nervous_banzai
06db4ceb8819   spcleth/serverless-benchmarks:build.local.python.3.7   "/sebs/entrypoint.sh…"   22 hours ago     Exited (0) 22 hours ago               modest_agnesi
a207caedcc94   hello-world                                            "/hello"                 28 hours ago     Exited (0) 28 hours ago               wizardly_chaplygin
(python-venv) jchigu@SeBS:~/serverless-benchmarks$

**Comment by mcopik** [comment]
@jchigu Thanks for the bug report! It will be fixed soon.

**Comment by mcopik** [comment]
Resolved with #136
