### ISSUE TITLE
Question about Go when running openwhisk_preparation.py

### ISSUE THREAD

**Issue by HelloWorldGitHubUser** [spcl/serverless-benchmarks#137]
Hi, when I run the script tools/openwhisk_preparation.py to install kind and deploy OpenWhisk on a kind cluster, no matter which version (1.16 or 1.17 or above) of Go I use, the same error appears :
```
# github.com/apache/openwhisk-cli/wski18n
../../../gowork/pkg/mod/github.com/apache/openwhisk-cli@v0.0.0-20230216141022-b1ca4bccc2c2/wski18n/i18n.go:98:16: undefined: Asset
ERROR:root:Cannot install wsk, reason: Command '['ln', '-sf', '/home/ubuntu/gowork/src/github.com/apache/openwhisk-cli/wsk', '/home/ubuntu/.local/bin/wsk']' returned non-zero exit status 1.
```
The only difference is that when I use version 1.17 and above, it seems that 'go get' command cannot be used normally:
`go get: installing executables with 'go get' in module mode is deprecated.`
But it still has the problem of "undefined Asset".

**Comment by pmzuk** [comment]
This script needs to be updated - I'll adapt it to the newest Go version.  In the meantime, you may also use other OpenWhisk installation methods mentioned in [the documentation](https://openwhisk.apache.org/documentation.html#openwhisk_deployment).

**Comment by HelloWorldGitHubUser** [comment]
ohhh ok,I'll try to deploy it by following the documentation and the guideline. And if it's necessary, you can close this issue.
thx both of u a lot :)

**Comment by mcopik** [comment]
Thanks @pmzuk for help :-)

**Comment by senju-hashirama** [comment]
Hey @pmzuk the script hasnt been updated to  use "go install" . Can this  be assigned to me I would like to work on it

**Comment by mcopik** [comment]
@senju-hashirama @pmzuk Hi, any update on this?

**Comment by mcopik** [comment]
Closing the issue due to inactivity.
