### ISSUE TITLE
"Faulty" benchmarks on OpenWhisk

### ISSUE THREAD

**Issue by alevy** [spcl/serverless-benchmarks#138]
**Describe the bug**
Several of the benchmarks result in HTTP error 400, and thus only run once, when using OpenWhisk configuration.

I'm sure I'm doing something wrong in my setup, but I wasn't able to find a step-by-step to setup the experiments for OpenWhisk so I'm kind of winging it.

**To Reproduce**

I'm using an OpenWhisk installation on CloudLab. Then, on the coordinator machine:

1. `./sebs.py storage start minio` to start minio
2. The following command to invoke a "faulty" benchmark

```sh
$ ./sebs.py benchmark invoke 311.compression test --config config/openwhisk.json --deployment openwhisk --verbose
12:37:02,261 INFO SeBS-261c: Created experiment output at /users/aalevy/serverless-benchmarks
12:37:02,269 INFO OpenWhisk.Resources-933c: Using cached Docker registry for OpenWhisk
12:37:02,269 INFO OpenWhisk.Resources-933c: Using user-provided configuration of storage for OpenWhisk.
12:37:02,270 INFO OpenWhisk.Resources-933c: User-provided configuration is different from cached storage, we will update existing OpenWhisk actions.
12:37:02,273 INFO Benchmark-e326: Using cached benchmark 311.compression at /users/aalevy/serverless-benchmarks/cache/311.compression/openwhisk/python/3.7/311.compression.zip
12:37:02,274 INFO OpenWhisk-1ea5: Using cached function 311.compression-python-3.7 in /users/aalevy/serverless-benchmarks/cache/311.compression/openwhisk/python/3.7/311.compression.zip
12:37:02,293 INFO OpenWhisk-1ea5: Updating function configuration due to changed storage configuration.
12:37:02,293 INFO OpenWhisk-1ea5: Update configuration of an existing OpenWhisk action 311.compression-python-3.7.
12:37:02,484 INFO minio.Minio-be75: Using cached storage input buckets ['311.compression-0-input-12aa2af9-f9f0-4a']
12:37:02,484 INFO minio.Minio-be75: Using cached storage output buckets ['311.compression-0-output-4610fa6f-2f7a-4a']
12:37:03,229 INFO SeBS-261c: Beginning repetition 1/5
12:37:16,971 ERROR OpenWhisk.HTTPTrigger-118e: Invocation on URL https://10.10.1.1:31001/api/v1/web/guest/default/311.compression-python-3.7.json failed!
12:37:16,971 ERROR OpenWhisk.HTTPTrigger-118e: Output: {'code': 'mrpYO4sAVlh0I2JUMr0icpHkIdYoBa5E', 'error': "Response is not valid 'application/json'."}
ERROR:root:Failed invocation of function! Output: {'code': 'mrpYO4sAVlh0I2JUMr0icpHkIdYoBa5E', 'error': "Response is not valid 'application/json'."}
Traceback (most recent call last):
  File "./sebs.py", line 30, in __call__
    return self.main(*args, **kwargs)
  File "/users/aalevy/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/users/aalevy/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/aalevy/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/aalevy/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/aalevy/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./sebs.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "./sebs.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "./sebs.py", line 250, in invoke
    ret = trigger.sync_invoke(input_config)
  File "/users/aalevy/serverless-benchmarks/sebs/openwhisk/triggers.py", line 99, in sync_invoke
    return self._http_invoke(payload, self.url, False)
  File "/users/aalevy/serverless-benchmarks/sebs/faas/function.py", line 215, in _http_invoke
    raise RuntimeError(f"Failed invocation of function! Output: {output}")
RuntimeError: Failed invocation of function! Output: {'code': 'mrpYO4sAVlh0I2JUMr0icpHkIdYoBa5E', 'error': "Response is not valid 'application/json'."}
INFO:Benchmark-7013:Update cached config /users/aalevy/serverless-benchmarks/cache/openwhisk.json
```

**Expected behavior**

I'm not entirely sure, since I'm running these for the first time, but I'd expect it to behave similarly to working benchmarks, such as `110.dynamic-html`:

```sh
$ ./sebs.py benchmark invoke 110.dynamic-html test --config config/openwhisk.json --deployment openwhisk --verbose
12:44:09,658 INFO SeBS-eb1f: Created experiment output at /users/aalevy/serverless-benchmarks
12:44:09,663 INFO OpenWhisk.Resources-6771: Using cached Docker registry for OpenWhisk
12:44:09,663 INFO OpenWhisk.Resources-6771: Using user-provided configuration of storage for OpenWhisk.
12:44:09,666 INFO Benchmark-c6cb: Using cached benchmark 110.dynamic-html at /users/aalevy/serverless-benchmarks/cache/110.dynamic-html/openwhisk/python/3.7/110.dynamic-html.zip
12:44:09,667 INFO OpenWhisk-4f46: Using cached function 110.dynamic-html-python-3.7 in /users/aalevy/serverless-benchmarks/cache/110.dynamic-html/openwhisk/python/3.7/110.dynamic-html.zip
12:44:09,685 INFO OpenWhisk-4f46: Cached function 110.dynamic-html-python-3.7 is up to date.
12:44:09,686 INFO minio.Minio-34ae: Using cached storage input buckets []
12:44:09,686 INFO minio.Minio-34ae: Using cached storage output buckets []
12:44:09,686 INFO SeBS-eb1f: Beginning repetition 1/5
12:44:13,292 INFO SeBS-eb1f: Beginning repetition 2/5
12:44:13,355 INFO SeBS-eb1f: Beginning repetition 3/5
12:44:13,417 INFO SeBS-eb1f: Beginning repetition 4/5
12:44:13,476 INFO SeBS-eb1f: Beginning repetition 5/5
12:44:13,541 INFO SeBS-eb1f: Save results to /users/aalevy/serverless-benchmarks/experiments.json
```

**System (please complete the following information):**
 - SeBS v1.1 (i've also tried with tip from f9acb398acb0419477381f011fab6f74411ef53a)
 - Python version 3.8
 - Ubuntu

**Comment by alevy** [comment]
Also, thank you for maintaining this so well!

**Comment by mcopik** [comment]
@alevy Thanks for raising the issue! Can you please tell me which benchmarks are failing?

One potential issue that comes to my mind is that your config is missing the storage configuration - a deployment of storage `minio` is independent of OpenWhisk benchmarks. Since OpenWhisk does not have its own storage, we need to "tell" functions how to access the storage (address, port, access keys). Did you [run the `jq` command](https://github.com/spcl/serverless-benchmarks/blob/master/docs/platforms.md#storage) to copy the storage JSON config into the OpenWhisk configuration? 

Overall, the error indicates that we did not return a correct JSON from the function invocation - likely, there was an unhandled exception. I don't know which k8s installation you are using - can you access the logs of the pod hosting the function?  [See an example](https://spacelift.io/blog/kubectl-logs) - this should make it much easier for me to debug the issue.

**Comment by alevy** [comment]
Thanks for the quick response. I'll try to get this info ASAP. I did setup minio (with some variation of that jq command and the start storage cmd from the docs). however it's entirely possible i did it incorrectly. The pointer to getting logs from k8s is great, I'm sure the logs will be much more informative.

**Comment by alevy** [comment]
You were exactly right, the minio instance is not accessible from the containers---I was using an incorrect IP address for the local machine (where minio is running).

I'm closing the issue, if that's OK. Thanks for your help!

I will be sending a _small_ PR with a slight correction to the documentation on setting up minio for OpenWhisk soon

**Comment by mcopik** [comment]
@alevy Great, waiting for the PR! 

I will reopen the issue - even though the issue was resolved, we should be able to catch an exception and return a proper response from the function. Right now we fail to generate a result which is not great for users - as you can see from this example :-)

**Comment by mcopik** [comment]
Fix pushed to `dev` - we now catch the exception and try to return the user a more helpful message. A full implementation is waiting for #118
