### ISSUE TITLE
"Permission \'cloudfunctions.functions.create\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7\' (or resource may not exist

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#152]
**Describe the bug**
I am receiving the above error when running a regression test on GCP region: us-east1
**To Reproduce**
1. Go to '...' : 
2. Run the command '....' : /sebs.py benchmark regression test --config config/example.json --deployment gcp
3. Scroll down to '....' : where the functions are 
4. See the error: 
WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "Permission \'cloudfunctions.functions.get\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7\' (or resource may not exist).",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "Permission \'cloudfunctions.functions.create\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7\' (or resource may not exist).",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
**Expected behavior**

**socket.timeout: The write operation timed out**
**requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))**

This command is supposed to deploy the benchmarks on GCP and return the results "executed 10 out of 10 functions" but it is executing zero out of 10.

**Logs**
Please provide the output of SeBS commands causing the problem, executed with the flag `--verbose`. Please use the Markdown fenced code blocks (``` ... ```) to format error logs.

(```WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "Permission \'cloudfunctions.functions.get\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7\' (or resource may not exist).",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "Permission \'cloudfunctions.functions.create\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7\' (or resource may not exist).",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'

-------------

sebs.regression.GCPTestSequence.test_120.uploader: fail
sebs.regression.GCPTestSequence.test_120.uploader: Traceback (most recent call last):
  File "/root/serverless-benchmarks/sebs/gcp/gcp.py", line 213, in create_function
    get_req.execute()
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudfunctions.googleapis.com/v1/projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7?alt=json returned "Permission 'cloudfunctions.functions.get' denied on resource 'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7' (or resource may not exist).">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/serverless-benchmarks/sebs/regression.py", line 50, in test
    func = deployment_client.get_function(
  File "/root/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/root/serverless-benchmarks/sebs/gcp/gcp.py", line 235, in create_function
    create_req.execute()
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudfunctions.googleapis.com/v1/projects/serverless-benchmarks/locations/us-east1/functions?alt=json returned "Permission 'cloudfunctions.functions.create' denied on resource 'projects/serverless-benchmarks/locations/us-east1/functions/function-120_uploader_python_3_7' (or resource may not exist).">

-------------

[11:21:14.925675] GCP-110b Uploading function function-311_compression_python_3_7 code to 311_compression-0-input-ab458f98-1514-49
WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "Permission \'cloudfunctions.functions.get\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-311_compression_python_3_7\' (or resource may not exist).",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'
WARNING:googleapiclient.http:Invalid JSON content from response: b'{\n  "error": {\n    "code": 403,\n    "message": "Permission \'cloudfunctions.functions.create\' denied on resource \'projects/serverless-benchmarks/locations/us-east1/functions/function-311_compression_python_3_7\' (or resource may not exist).",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'

-------------

sebs.regression.GCPTestSequence.test_311.compression: fail
sebs.regression.GCPTestSequence.test_311.compression: Traceback (most recent call last):
  File "/root/serverless-benchmarks/sebs/gcp/gcp.py", line 213, in create_function
    get_req.execute()
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudfunctions.googleapis.com/v1/projects/serverless-benchmarks/locations/us-east1/functions/function-311_compression_python_3_7?alt=json returned "Permission 'cloudfunctions.functions.get' denied on resource 'projects/serverless-benchmarks/locations/us-east1/functions/function-311_compression_python_3_7' (or resource may not exist).">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/serverless-benchmarks/sebs/regression.py", line 50, in test
    func = deployment_client.get_function(
  File "/root/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/root/serverless-benchmarks/sebs/gcp/gcp.py", line 235, in create_function
    create_req.execute()
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://cloudfunctions.googleapis.com/v1/projects/serverless-benchmarks/locations/us-east1/functions?alt=json returned "Permission 'cloudfunctions.functions.create' denied on resource 'projects/serverless-benchmarks/locations/us-east1/functions/function-311_compression_python_3_7' (or resource may not exist).">  ```)

**System (please complete the following information):**
 - SeBS version (release, branch, git commit) - git clone 
 - Python version - Python 3.8.10
 - OS - Linux ubuntu 20:04 LTS

**Additional context**

**Comment by mcopik** [comment]
@jchigu There are two possible sources of this issue - either the function has not been created, or you do not have permission to access it. Looking at the log, SeBS fails [while attempting to create the function](https://github.com/spcl/serverless-benchmarks/blob/master/sebs/gcp/gcp.py#L235).

The problem seems to be that your Google Cloud project does not have sufficient permissions to create functions. Did you create a service account, as mentioned in the docs? You need to inspect the project in the GCP console; for your project, you should see something similar in the permissions tab - the last one is a service account attached to this project. As you can see, it has permission to manage cloud functions.

![image](https://user-images.githubusercontent.com/720619/235436991-40a42498-749a-4b58-a96e-a7bf0e19f65e.png)

You can find a step-by-step tutorial [here](https://www.serverless.com/framework/docs/providers/google/guide/credentials).

**Comment by mcopik** [comment]
@jchigu Any updates? Does the issue still occur? Do you know what solved the problem?

**Comment by mcopik** [comment]
@jchigu Does the issue still persist?

**Comment by mcopik** [comment]
@jchigu Does the issue still persist?
