### ISSUE TITLE
configuring example.json for benchmarking on GCP

### ISSUE THREAD

**Issue by mariechu3** [spcl/serverless-benchmarks#154]
Hi, I'm interesting in using SeBS but am very new to cloud computing and benchmarking. I was trying to follow the instructions on the `README` and ran the regression test but it failed with the results that I pasted below. Looking into the error I believe it's due to the fact that I configured the `example.json` file incorrectly. I'm unsure what exactly the "credentials" for gcp should be. I tried the "OAuth 2 Client ID", "Key ID", and the path to the json file for the service account that was generated but all of them seem to still result in the failed test. 
<img width="1280" alt="Screen Shot 2023-05-01 at 9 13 00 PM" src="https://user-images.githubusercontent.com/44188443/235577857-d9d281f8-56cf-4316-9a25-c77788f11b4d.png"> 

Additionally I was wondering for running these benchmarks is it sufficient to clone the repository onto my local machine and run the different experiments on my local machine or am I supposed to create an instance in gcp and clone the repo to that instance to run commands such as `./sebs.py experiment invoke perf-cost --config config/example.json --deployment gcp` in `cloud shell`?

**Comment by mariechu3** [comment]
I see, thank you for the clarification. My python venv is active when I run the regression test and I checked that install.py also added the export lines to my `python-venv/bin/activate` file. I also change the `config/example.json` to have:

```
"gcp": {
      "region": "us-west1",
      "project_name": "{GCP-Project-ID}",
      "credentials": "{absolute path to json key's file produced by the service account generation}"
    },
```

before running `./sebs.py experiment invoke perf-cost --config config/example.json --deployment gcp`

**Comment by mcopik** [comment]
@mariechu3 The configuration is correct, and the error message indicates that SeBS does not see support for GCP. What do you see when running this command?

```
echo ${SEBS_WITH_GCP}
```

**Comment by mariechu3** [comment]
<img width="648" alt="Screen Shot 2023-05-15 at 10 00 02 AM" src="https://github.com/spcl/serverless-benchmarks/assets/44188443/2bc211ae-40bc-4448-9e65-e80942a6f06b">

**Comment by mcopik** [comment]
@mariechu3 I am really surprised by this. Does the issue persist if your `python-venv` is activated and you run without `sudo`?

**Comment by mcopik** [comment]
@mariechu3 Can you please apply this patch, run the regression test again, and show the beginning of the output?  Look for lines `WARNING:root:SEBS_WITH_GCP`.
[patch.txt](https://github.com/spcl/serverless-benchmarks/files/11480554/patch.txt)

**Comment by mariechu3** [comment]
I've been running the regression tests with `sudo` since I got some permission error with Docker without it and applying the patch and running the regression test gives me something of the form:  `WARNING:root:SEBS_WITH_GCP , value loaded false`

**Comment by mcopik** [comment]
@mariechu3 Looks like interference of `sudo` - you can run without sudo by adding your user to the `docker` group, e.g., see [here](https://docs.docker.com/engine/install/linux-postinstall/). I hope this will resolve the issue.

**Comment by mariechu3** [comment]
That resolved the issue and the regression test runs now! Thank you for your help!

**Comment by mcopik** [comment]
You're welcome, happy to hear it works! :)
