### ISSUE TITLE
Faced error while running ./install.py

### ISSUE THREAD

**Issue by nervermore2** [spcl/serverless-benchmarks#157]
Hi,
I was able to run the benchmark on mac os, but not on a fresh Amazon Ubuntu based image.
what I did on a fresh ec2 instance: 
```
sudo ln /usr/bin/python3 /usr/bin/python
sudo apt-get install zip
sudo apt install python3-pip
sudo apt-get install python3.10-venv
pip install --upgrade virtualenv
```
I met the following error while running ./install.py --aws --azure --gcp
```
Using existing Python virtualenv at python-venv
Install Python dependencies with pip
Traceback (most recent call last):
  File "/home/ubuntu/masters/serverless-benchmarks-master/./install.py", line 39, in <module>
    execute(". {}/bin/activate && pip3 install -r requirements.txt --upgrade".format(env_dir))
  File "/home/ubuntu/masters/serverless-benchmarks-master/./install.py", line 24, in execute
    raise RuntimeError(
RuntimeError: Running . python-venv/bin/activate && pip3 install -r requirements.txt --upgrade failed!
 Output: /bin/sh: 1: .: cannot open python-venv/bin/activate: No such file
```

**Comment by nervermore2** [comment]
So I'm wondering what would be the proper process if I want to transfer and run it on a dev desktop, like EC2 or GCP instance if I was able to let it run locally?

Thanks

**Comment by nervermore2** [comment]
Hi, I was able to resolve it by removing the virtual environment and re run the installation again.

**Comment by mcopik** [comment]
@nervermore2 Yes, the error indicates that your virtual environment is missing the Python interpreter. Recreating the environment was the right decision :)

**Comment by nervermore2** [comment]
Thanks. A side question (or this might not be a proper place to ask you a side question maybe?): what is the difference between a perf-cost test and a regression test? I could find a definition. Thanks!

**Comment by mcopik** [comment]
@nervermore2 `perf-cost` is one of the experiments we implemented to gather statistical measurements for our paper. Functions are executed in batches and in many configurations, and we take multiple time measurements.

Regression tests are used only to verify that functions work correctly :)
