### ISSUE TITLE
Clear definitions between benchmark and experiment

### ISSUE THREAD

**Issue by nervermore2** [spcl/serverless-benchmarks#159]
When reading the README files and reading the code, it's uneasy to find the clear definitions between `./sebs experiment` and `./sebs benchmark`. Is it possible to provider more info about either in README or in the command line help parameter? 

Thanks

**Comment by mcopik** [comment]
@nervermore2 [We have a short tutorial explaining the usage of these CLI options](https://github.com/spcl/serverless-benchmarks/blob/master/docs/usage.md), but it was incorrectly linked in our README - I fixed it.

Is this sufficient? Let me know what else would you add - happy to fix it.

**Comment by nervermore2** [comment]
It's enough. I did some experiments with the CLI options and I figure all of them out. Thanks!
