### ISSUE TITLE
Error while running 120.upload

### ISSUE THREAD

**Issue by nervermore2** [spcl/serverless-benchmarks#162]
When running 120.upload on gcp, nodejs 14 with 512 MB memoy: I got following error
```
function-120_uploader_nodejs_101w2zxks5h2ao ResumableUploadError: A resumable upload could not be performed. The directory, /root/.config, is not writable. You may try another upload, this time setting `options.resumable` to `false`. at fs.access.err (/workspace/node_modules/@google-cloud/storage/build/src/file.js:1265:39) at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```
I tried with another benchmark, 110.dynamic-html. This works. So it seems like it's an benchmark code specific error

**Comment by nervermore2** [comment]
Today, both 120.uploader and 210.thumbnailer failed on gcp with same error 
```
SyntaxError: Identifier 'bucket' has already been declared at wrapSafe (internal/modules/cjs/loader.js:1029:16) at Module._compile (i
```

**Comment by mcopik** [comment]
@nervermore2 Which Node.js did you use?

**Comment by mcopik** [comment]
@nervermore2 And this is on GCP?

**Comment by nervermore2** [comment]
I believe I use node 14 and yes this is on GCP

**Comment by mcopik** [comment]
@nervermore2 This problem has been reproduced by me and fixed on the `dev` branch. It will be merged with the master soon. Meanwhile, you can use the development branch.
