### ISSUE TITLE
Need to add requirements.txt.3.8 to python benchmark 210

### ISSUE THREAD

**Issue by nervermore2** [spcl/serverless-benchmarks#163]
210.thumnailer requires Pillow library for python. Currently, we are missing the for python3.8.

**Comment by mcopik** [comment]
@nervermore2 Thanks for raising the issue! Indeed, the bug has been fixed in the `hotfix` branch.

It will be merged with the master soon.

**Comment by mcopik** [comment]
Merged with master.
