### ISSUE TITLE
Succesfully executed 0 out of 0 functions - openwhisk

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#171]
''' when I run regression test on openwhisk this is what I am getting. Is there documentation specific to SeBS showing step by step process to follow:

(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ ./sebs.py benchmark regression test --config config/openwhisk.jso
n --deployment openwhisk
[09:09:28.642295] SeBS-3542 Created experiment output at /home/j/serverless-benchmarks/regression-output
Succesfully executed 0 out of 0 functions
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$

**Comment by mcopik** [comment]
Closing as duplicate of #147
