### ISSUE TITLE
'Visualisation' typo in documentation

### ISSUE THREAD

**Issue by nurSaadat** [spcl/serverless-benchmarks#174]
**Describe the bug**
In the docs for benchmarks the title of the benchmark is said to be 'visualization', while in fact it is 'visualisation'. It may cause confusion when trying to run experiments by copy-pasting file names from docs.

**Comment by mcopik** [comment]
@nurSaadat Thank you for catching this! I will review in coming days our benchmark documentation to verify there are no other pending issues.

Feel free to open a PR to fix this or any other documentation issues you might have found :)
