### ISSUE TITLE
Documentation for outputted results

### ISSUE THREAD

**Issue by nurSaadat** [spcl/serverless-benchmarks#180]
Hello!

I was running perf-cost experiment and I still don't understand if I am getting my measurements right. I am using the generated result.csv to build box-and-whiskers graphs and the time metric looks weird. I'd like to ask, what is the unit of measure for time that I can see in my result.csv table? Are those milliseconds or seconds? 

I get some ridiculously big time measurements, I was sure those were milliseconds, but dividing them by 1000 didn't help that much. I am attaching some files and graph pictures to see the results of the experiments I performed. 
UPD: 
- The name is above the figure. 
- The time value is already divided by 1000
- Those are warm invocations, exec_time (benchmark time)

amazon_compression
![amazon_compression](https://github.com/spcl/serverless-benchmarks/assets/39532643/cfed2fe5-b32e-4a54-b0ff-49c7244ca6c1)

amazon_thumbnailer
![amazon_thumbnailer](https://github.com/spcl/serverless-benchmarks/assets/39532643/1a628a20-6015-4258-9bf0-eb9e10e0d3fa)

amazon_uploader
![amazon_uploader](https://github.com/spcl/serverless-benchmarks/assets/39532643/cfcf4d92-7556-47b4-9e57-1ca904d0416b)

azure_compression
![azure_compression](https://github.com/spcl/serverless-benchmarks/assets/39532643/2e9118a4-b1c4-49d5-bb6b-80faede40682)

azure_thumbnailer
![azure_thumbnailer](https://github.com/spcl/serverless-benchmarks/assets/39532643/4c62bfb9-5c99-46e9-99c1-f31f01453050)

azure_uploader
![azure_uploader](https://github.com/spcl/serverless-benchmarks/assets/39532643/a7833774-9f54-4970-8b7a-bc5ee471d67f)

google_compression
![google_compression](https://github.com/spcl/serverless-benchmarks/assets/39532643/a92c2019-8a27-4588-9acf-67a18c4648a5)

google_thumbnailer
![google_thumbnailer](https://github.com/spcl/serverless-benchmarks/assets/39532643/8d10ae42-a173-4441-8a49-4172bebd1831)

google_uploader
![google_uploader](https://github.com/spcl/serverless-benchmarks/assets/39532643/2683ab9d-ab84-43d4-896a-467014e51b31)

[azure_uploader.csv](https://github.com/spcl/serverless-benchmarks/files/12560728/azure_uploader.csv)
[azure_thumbnailer.csv](https://github.com/spcl/serverless-benchmarks/files/12560729/azure_thumbnailer.csv)
[azure_compression.csv](https://github.com/spcl/serverless-benchmarks/files/12560730/azure_compression.csv)
[amazon_compression.csv](https://github.com/spcl/serverless-benchmarks/files/12560731/amazon_compression.csv)
[google_compression.csv](https://github.com/spcl/serverless-benchmarks/files/12560732/google_compression.csv)
[google_thumbnailer.csv](https://github.com/spcl/serverless-benchmarks/files/12560733/google_thumbnailer.csv)
[amazon_uploader.csv](https://github.com/spcl/serverless-benchmarks/files/12560737/amazon_uploader.csv)
[google_uploader.csv](https://github.com/spcl/serverless-benchmarks/files/12560734/google_uploader.csv)
[amazon_thumbnailer.csv](https://github.com/spcl/serverless-benchmarks/files/12560735/amazon_thumbnailer.csv)

**Comment by nurSaadat** [comment]
@mcopik I would love to hear your opinion on this matter

**Comment by nurSaadat** [comment]
The problem is, I am trying to replicate your paper results for a reproducibility challenge, but the results are not the same and I have no idea how to get there

**Comment by mcopik** [comment]
@nurSaadat We updated the main branch with new and expanded documentation on the benchmarks. We now clearly state that all time measurements are in `microseconds`.

Hope it helps - please let me know via email or here if there's anything else that is missing in our documentation or incorrect, we'll fix it!

**Comment by nurSaadat** [comment]
@mcopik Thank you very much! That clears my concerns.
