### ISSUE TITLE
Deployment {name} not supported!

### ISSUE THREAD

**Issue by im-rikesh** [spcl/serverless-benchmarks#187]
Hi, everyone.

I wanted to use SeBS with OpenWhisk. I followed the instructions in the [https://github.com/spcl/serverless-benchmarks/blob/master/README.md#installation](https://github.com/spcl/serverless-benchmarks/blob/master/README.md#installation) document. When I tried to run any function in OpenWhisk, it shows me this error "_/serverless-benchmarks/sebs/sebs.py", line 109, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!_"

Below is the attached screenshot.

![image](https://github.com/spcl/serverless-benchmarks/assets/35441207/4c156d98-8596-4d97-bd85-0106c9ef7230)

I have also set up the configurations for OpenWhisk in the config/local_deployment.json file. I would be really glad if you could help.

Thank You!

**Comment by mcopik** [comment]
@im-rikesh Hi! Thanks for using SeBS :-)

This means that your Python environment. There are two likely reasons for this problem:
(1) When running install.py, you didn't include the `--openwhisk` flag.
(2) You are not using the virtual environment created by installation.
See our [installation documentation](https://github.com/spcl/serverless-benchmarks/blob/master/README.md#installation) for details.

The `sudo` command might add to the problems when running within a virtual environment. I heavily recommend configuring your Docker daemon (details in docs above) and not running SeBS as the super-user.

**Comment by mcopik** [comment]
@im-rikesh Does the issue persist?
