### ISSUE TITLE
Errors running basic setup commands

### ISSUE THREAD

**Issue by MinhThieu145** [spcl/serverless-benchmarks#188]
**Describe the bug**
While setting up a project, I encountered an issue with unrecognized command-line options during the execution of Python scripts. Initially, I ran `./install.py --aws` and subsequently executed `./sebs.py benchmark invoke 110.dynamic-html test --config config/example.json --deployment aws --verbose`. Both commands generated warnings indicating that certain options were not recognized and were being passed to Electron/Chromium.

**Steps to Reproduce:**
1. Execute the command `./install.py --aws` in the PowerShell within the project directory `C:\Users\Thieu\Desktop\GG Summer Code\serverless-benchmarks`.
   - This results in the following warning:
     ```
     Warning: 'aws' is not in the list of known options, but still passed to Electron/Chromium.
     ```
2. Execute the command `./sebs.py benchmark invoke 110.dynamic-html test --config config/example.json --deployment aws --verbose`.
   - This results in the following warnings:
     ```
     Warning: 'config' is not in the list of known options, but still passed to Electron/Chromium.
     Warning: 'deployment' is not in the list of known options, but still passed to Electron/Chromium.
     ```

**Additional Context:**
- The issue persists even after manually setting up the Conda environment and installing the required packages using `requirements.aws.txt`.
- The environment seems to be influenced by Electron/Chromium, as indicated by the warnings and subsequent logs related to policy configurations and file watchers, suggesting an interaction with VS Code or a similar tool.

**Expected Behavior:**
The script should recognize and process the `--aws`, `--config`, and `--deployment` options without issuing warnings or passing them to unrelated processes or applications.

**Actual Behavior:**
The script issues warnings that the mentioned options are unrecognized and being passed to Electron/Chromium, indicating a possible conflict or misinterpretation in the execution environment.

**Environment:**
- OS: Windows (PowerShell execution context)
- Involved scripts: `install.py` and `sebs.py`
- Possibly related applications: Electron, Chromium, VS Code

**Comment by mcopik** [comment]
@MinhThieu145 Hi! Thank you for the detailed bug report.

Generally, we support only Linux/POSIX systems with Bash shell. I have never tried the PowerShell, and I don't know where the Electron/Chromium is coming from - are you by any chance running the shell from VSCode?

I recommend trying the WSL on your Windows machine, as I doubt that you will be able to run SeBS without a proper Bash interpreter. If this doesn't work for you, please let me know - we can debug the issue together.

**Comment by MinhThieu145** [comment]
> @MinhThieu145 Hi! Thank you for the detailed bug report.
> 
> Generally, we support only Linux/POSIX systems with Bash shell. I have never tried the PowerShell, and I don't know where the Electron/Chromium is coming from - are you by any chance running the shell from VSCode?
> 
> I recommend trying the WSL on your Windows machine, as I doubt that you will be able to run SeBS without a proper Bash interpreter. If this doesn't work for you, please let me know - we can debug the issue together.

@mcopik Hi! Thanks for the suggestion to use WSL with VS Code. I followed your advice and it worked perfectly on my Windows machine.

**Comment by mcopik** [comment]
@MinhThieu145 I'm glad to hear it works! In PR #190, I amended our documentation to guide new Windows users towards WSL.

Thank you for raising the issue!
