### ISSUE TITLE
Test single bucket design

### ISSUE THREAD

**Issue by mcopik** [spcl/serverless-benchmarks#195]
SeBS originally used different storage buckets for each benchmark, which can lead to problems on AWS - S3 has a hard limit of 100 buckets per account (#185). In [branch single-bucket](https://github.com/spcl/serverless-benchmarks/tree/feature/single-bucket), we developed a new system where SeBS uses three buckets only: one for deploying code, one for benchmarks input/output, and one for experiments. We also added a system to cache and reuse those buckets properly between different SeBS installations.

Now, we want to run our regression testing (`./sebs.py regression ...`) to verify that the new system works on all platforms. All help is appreciated!
- [x] Test AWS regression.
- [x] Test Azure.
- [x] Test GCP.
- [x] Test Openwhisk + Local.

**Comment by LahiruOshara** [comment]
@mcopik is it possible to provide some guidance for this issue?

**Comment by mcopik** [comment]
@LahiruOshara I'm closing down on this issue currently :) If you want to help with updating SeBS to newer versions and features, then you can help in issue #196 - we need help with verifying on platforms like OpenWhisk!
