### ISSUE TITLE
Updating support for benchmark language versions

### ISSUE THREAD

**Issue by mcopik** [spcl/serverless-benchmarks#196]
Since our last release, certain language runtimes have been deprecated, and new ones have been added. In preparation for the next release, we now need to prune the language versions that are no longer supported and add new ones.

We should drop the support for Python/Node.js which are no longer deployable to clouds; this change should be done separately for each cloud, e.g., drop Python 3.7 where it's no longer supported. 

Systems/languages to support; 
- [x] AWS, Python
- [x] AWS, Node.js
- [x] Azure, Python
- [x] Azure, Node.js
- [x] GCP, Python
- [x] GCP, Node.js
- [x] OpenWhisk, Python
- [x] OpenWhisk, Node.js

**Comment by octonawish-akcodes** [comment]
Can i get some more guidance here like what files I should look up to?

**Comment by mcopik** [comment]
@octonawish-akcodes All definitions of supported language versions are in the `config/systems.json`. To add support for new versions, you need to verify that Docker images build for it.

**Comment by octonawish-akcodes** [comment]
I tried to remove the AWS 3.7 python support since its no longer supported and raised a PR #198 @mcopik

**Comment by mcopik** [comment]
Fixed with #198
