### ISSUE TITLE
How SeBS could be used with Fission?

### ISSUE THREAD

**Issue by YasminBZ** [spcl/serverless-benchmarks#69]
Hello, 

I would like to know how to use SeBS with Fission please.

I appreciate your help.

Thank you.

**Comment by mcopik** [comment]
@YasminBZ We're working on the support for open-source platforms, it is planned for next releases.

There's a branch with support for Fission partially implemented: https://github.com/spcl/serverless-benchmarks/tree/feature_fission

**Comment by mcopik** [comment]
We have ongoing progress toward running SeBS benchmarks on Fission. A good first step would be clean the branch and update it to the current interface.

**Comment by Stazz0** [comment]
![Screenshot from 2024-02-28 00-14-31](https://github.com/spcl/serverless-benchmarks/assets/135238436/2a3f9d6b-e7bf-431a-b91b-7b0561d5416a)
"Hi @mcopik, I ran into a ".gitignore" conflict while updating feature_fission branch. Could you take a look at the conflict and let me know how to resolve it? Thanks for your help!"

**Comment by Stazz0** [comment]
Regarding my earlier question about the .gitignore conflict I found that removing the 'sebs-*', 'cache', and '.vscode' entries is a common solution. Would this work for our project, or do you suggest a different approach? Thanks!
@mcopik

**Comment by Stazz0** [comment]
Hii @mcopik , I'm encountering a number of errors during the feature_fission branch update. It seems to be related to whitespace issues and merge conflicts in .gitignore, sebs.py, s3.py. Could you advise me on the best way to resolve these – keeping both changes, or choosing one? Thanks in advance!
![Screenshot from 2024-02-28 00-14-31](https://github.com/spcl/serverless-benchmarks/assets/135238436/3b3d25f3-2e68-4055-97ff-8a09fc50b06d)

**Comment by mcopik** [comment]
@Stazz0 Hi! Thanks for your interest in the project and apologies for the slow reply.

Since this branch is quite old, I'm afraid I will have to take a look into this - we've had many breaking changes over the years. I will try to update the branch as soon as possible.

**Comment by mcopik** [comment]
@Stazz0 The branch should be up-to-date with the master. Please merge instead of rebasing on this branch, as it was created a long time ago and we had many conflicts resolved over that time.

**Comment by mcopik** [comment]
Closing this issue in favor of #61 - @prajinkhadka is working on this currently.
