### ISSUE TITLE
Regression for the NodeJS benchmarks

### ISSUE THREAD

**Issue by mcopik** [spcl/serverless-benchmarks#78]
Our regression tests don't include NodeJS benchmarks at the moment, and this should be fixed.

**Comment by DiviyamPathak** [comment]
doesn't this #166 closes this , is there something more to do ? if yes would be happy to help given some guidance

**Comment by mcopik** [comment]
@DiviyamPathak Yes, it seems that this issue is resolved but we forgot to close it - thank you! :-) Let me know if you need suggestions for other issues to fix.
