### ISSUE TITLE
`black` latest version has conflicts with `click==7.1.2` 

### ISSUE THREAD

**Issue by Dpac99** [spcl/serverless-benchmarks#83]
# Problem
Got this error when installing:
> ERROR: Cannot install -r requirements.txt (line 8) and click==7.1.2 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested click==7.1.2
    black 22.1.0 depends on click>=8.0.0

# Possible Fix
Remove the `click==7.1.2` requirement. This seems like it was included to prevent older versions of `click` from being used as `black@20.8b1` explicitly requires it

**Comment by mcopik** [comment]
@Dpac99 Thank you for raising the issue! The fix has been applied to master (#84)
